### ISSUE TITLE
Bulk render names with spaces instead of underscores

### ISSUE THREAD

**Issue by elifoster** [unascribed/BlockRenderer#1]
It would be a lot more useful, especially over at the FTB Gamepedia, if it would save the file names using the "pure" names instead of each space being replaced by underscores.

**Comment by exaskye** [comment]
I'll add spaces to the whitelist. I mainly run Linux, and spaces are somewhat annoying to work with on the command line, so I generally consider them an "illegal" character when sanitizing filenames.
