### ISSUE TITLE
Unmark as experimental

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#10]
On CurseForge, please unmark this project as experimental. Also, 1.10- there's nothing you have to do I believe, other than change the version number.

**Comment by exaskye** [comment]
I can't just unmark it, it has to get re-approved.
And I'm aware 1.10 doesn't usually require updating. I'll add 1.10 to the supported versions if you verify it works.

**Comment by xbony2** [comment]
I messed with it in Unstable, and it worked fine. Thanks.
