### ISSUE TITLE
Mark latest version as 1.11.2

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#16]
(98% sure it should work)

**Comment by exaskye** [comment]
Done, please confirm it works and I will close the issue.

**Comment by xbony2** [comment]
Seems to work 👍

**Comment by exaskye** [comment]
I said **I** would close the issue. >:(

**Comment by xbony2** [comment]
suk it

**Comment by elifoster** [comment]
It's okay @unascribed I'm on your side

![screen shot 2017-01-09 at 5 42 35 pm](https://cloud.githubusercontent.com/assets/4176124/21790729/246e9922-d693-11e6-9581-38de44421e79.png)

**Comment by xbony2** [comment]
ew that black theme is disgusting

**Comment by elifoster** [comment]
It doesn't burn my eyes when I GitHub pre-caffeine in the morning.

**Comment by xbony2** [comment]
I never drink coffee and it looks terrible always.
