### ISSUE TITLE
Maven version can't run on 1.12.2

### ISSUE THREAD

**Issue by codetaylor** [unascribed/BlockRenderer#20]
The maven version listed on the curseforge page requires an older version of MC:

```
repositories {
    maven {
        name = 'unascribed'
        url = 'http://unascribed.com/maven/releases'
    }
}
dependencies {
    deobfCompile 'com.unascribed:blockrenderer:0.3.3'
}
```

Will this be updated?

Thanks for this mod! :)

**Comment by exaskye** [comment]
I don't publish non-library mod releases to a Maven repo anymore; please let me know if it would still be useful for your workflow to resume doing so and I'll reopen.
