### ISSUE TITLE
Renders appear too far up when the window is taller than normal

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#3]
[Here](https://i.imgur.com/iy4F7hG.png)'s a picture of that Chest that was dumped. It's a bit too high for whatever reason. I'm not sure what resolution my Minecraft windows is, but I don't think it's too small.

(Tested on FTB Unstable, probably not the best environment)

**Comment by exaskye** [comment]
<s>My guess here is Mesa (the open-source driver that I use) and whichever driver you're using (probably a Windows proprietary) have a different coordinate-space for readPixels. Not sure if I would classify that as a Mesa bug or a bug in whichever proprietary driver, but I'll look into a workaround.</s>

Nope. I'm just an idiot. Read the commit message for more details.

**Comment by xbony2** [comment]
I use a mac :o though it's a NVIDIA GeForce GT 120 512 MB.
