### ISSUE TITLE
1.9?

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#5]
Not to be one of ~those~ people, but do you plan to port this mod to 1.9?

**Comment by exaskye** [comment]
Once 1.9 Forge actually works, probably. It's impressively immature at the moment and almost nothing works properly.

**Comment by elifoster** [comment]
@unascribed So, does @95e1444 imply that Forge 1.9 actually works?

**Comment by exaskye** [comment]
@elifoster People in #minecraftforge seem to believe it works pretty well now, most of the registry idiocy is figured out, entities aren't broken, chunk errors are less frequent, etc. Basically the last thing left is interact events.

Also, updating this mod was laughably easy.
