### ISSUE TITLE
Ctrl+Render while hovering a slot should pre-fill the owning mod's ID

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#6]
It would be cool if, say, doing CTRL + the Dump Render key over a specific item would dump all of the icons in the mod, as a shortcut.

I should probably get off my lazy ass and send a few PRs instead of bugging you to do everything :P

**Comment by elifoster** [comment]
What would be done about the render size though?

**Comment by xbony2** [comment]
It could put up the interface with the mod ID already filled in I guess.

**Comment by xbony2** [comment]
[merp](http://ftb.gamepedia.com/BlockRenderer) ;3
